---
language: ruby
script: "bundle exec qed demo"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - rbx
  - rbx-19mode
  - jruby
  - jruby-19mode
env:
  - "minitest=4"
  - "minitest=5"
gemfile: 
  - "demo/Gemfile"


